        name: Node.js CI

        on:
          push:
            branches: [ main ]
          pull_request:
            branches: [ main ]

        jobs:
          build:
            runs-on: ubuntu-latest

            steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '16'

            - name: Install dependencies
              run: npm install

            - name: Start server
              run: |
                nohup node index.js > server.log 2>&1 &
                sleep 10 # Give the server some time to start

            - name: Verify server is running
              run: |
                if curl --silent --fail http://localhost:3000; then
                  echo "Server is running"
                else
                  echo "Server failed to start"
                  exit 1
                fi
              env:
                CI: true

            - name: Run tests
              run: npm test